#!/usr/bin/env bash


# Surrounding in brackets ensures that the whole script gets loaded to memory
# before running which allows us to update the script from the script without
# issue.
{
set -eu -o pipefail


# Let's make some pretty stuff
COLOR_RESET="$(tput sgr0)"
COLOR_BLACK="$(tput setaf 0)"
COLOR_RED="$(tput setaf 1)"
COLOR_GREEN="$(tput setaf 2)"
COLOR_YELLOW="$(tput setaf 3)"
COLOR_BLUE="$(tput setaf 4)"
COLOR_MAGENTA="$(tput setaf 5)"
COLOR_CYAN="$(tput setaf 6)"
COLOR_WHITE="$(tput setaf 7)"
TEXT_BOLD="$(tput bold)"
SYMBOL_TICK="✔"
SYMBOL_CROSS="✖"
SYMBOL_WARN="⚠"

log_ok() {
    echo "${COLOR_GREEN}${SYMBOL_TICK}${COLOR_RESET} $@ ${COLOR_RESET}"
}

log_warn() {
    echo "${COLOR_YELLOW}${SYMBOL_WARN}${COLOR_WHITE} $@ ${COLOR_RESET}"
}

log_err() {
    echo "${COLOR_RED}${SYMBOL_CROSS}${TEXT_BOLD}${COLOR_WHITE} $@ ${COLOR_RESET}"
}

echo $@

shell_reset() {
    unset -f log_ok log_warn log_err shell_reset
}

shell_reset
}
